package:
  name: node-red-global-state
  version: 1.0.9
  description: empty
  author: klein
  dependencies:
    mqtt: 3.0.0
  homepage: empty
  nodes:
    - from: states/state
    - from: states/device
    - from: states/mqtt
      to: mqtt
    - from: automation/smartLighting
  resources:
    - id: baseClasses
      from: states/statePrimitives.js
    - id: extractStates
      from: states/extractStates.js
