defaults: &defaults
  working_directory: /tmp

version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker run --name tmp -v $(pwd)/template:/data kezziny/node-red-module-generator:latest
      - persist_to_workspace:
          root: ./template
          paths: lib
  integration:
    machine: true
    steps:
      - checkout
      - run: .circleci/integrate.sh
  deploy:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - attach_workspace:
          at: ~/build
      - run: ls -la ~
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/build/lib/.npmrc
      - run:
          name: Publish package
          command: cd ~/build/lib && npm publish
workflows:
  version: 2
  integrate:
    jobs:
      - build:
      - start_integration:
          type: approval
          filters:
              branches:
                ignore:
                  - master
      - integration:
          requires:
            - start_integration
            - build
      - start_deploy:
          type: approval
          filters:
              branches:
                only:
                  - master
      - deploy:
          requires:
            - build
            - start_deploy
