defaults: &defaults
  working_directory: /tmp

version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker run -v .:/data kezziny/node-red-module-generator:latest
  integration:
    machine: true
    steps:
      - checkout
      - run: .circleci/integrate.sh
workflows:
  version: 2
  integrate:
    jobs:
      - start_build:
          filters:
            branches:
              ignore:
                - master
          type: approval
      - build:
          requires:
            - start_build
      - start_integration:
          type: approval
      - integration:
          requires:
            - start_integration
            - build
          filters:
            branches:
              ignore:
                - master
